#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

echo ">>> Installing Homebrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo ">>> Updating homebrew"
brew update

echo ">>> Installing core packages"
brew install \
	ag wget tree legit hub ctags \
	git pyenv stormssh redis \
	tmux tree unrar zsh zsh-completions \
	the_silver_searcher git-extras \
	heroku mysql

echo ">>> Installing bash fuzzy search"
brew install fzf
# Install shell extensions
/usr/local/opt/fzf/install

echo ">>> Installing zsh"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
curl -L https://iterm2.com/misc/`basename $SHELL`_startup.in \
-o ~/.iterm2_shell_integration.`basename $SHELL`

echo ">>> Installing trash"
npm install -g trash-cli

echo ">>> Installing reattach-to-user-namespace for tmux/macos copy/paste"
brew install reattach-to-user-namespace

echo ">>> Installing facebook fpp"
brew update; brew install fpp; fpp

echo ">>> Installing tmux pluging manager"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

